CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Players" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" integer NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("Id")
);

CREATE TABLE "Teams" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" integer NOT NULL,
    "Name" text NULL,
    "LogoPath" text NULL,
    "Description" text NULL,
    "WebsiteUrl" text NULL,
    "Contact" text NULL,
    "Country" text NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "DeleteDate" timestamp without time zone NULL,
    "Active" boolean NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
);

CREATE TABLE "TeamPlayerAssignmentEntity" (
    "PlayerId" integer NOT NULL,
    "TeamId" integer NOT NULL,
    "InviteDate" timestamp without time zone NOT NULL,
    "ResponseDate" timestamp without time zone NULL,
    "LeaveDate" timestamp without time zone NULL,
    "Accepted" boolean NOT NULL,
    "Active" boolean NOT NULL,
    CONSTRAINT "PK_TeamPlayerAssignmentEntity" PRIMARY KEY ("TeamId", "PlayerId"),
    CONSTRAINT "FK_TeamPlayerAssignmentEntity_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeamPlayerAssignmentEntity_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TeamPlayerAssignmentEntity_PlayerId" ON "TeamPlayerAssignmentEntity" ("PlayerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210123225630_InitMigration', '5.0.1');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210220012446_ChangedUserIdToString', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Teams" ALTER COLUMN "OwnerId" TYPE text;
ALTER TABLE "Teams" ALTER COLUMN "OwnerId" DROP NOT NULL;

ALTER TABLE "Players" ALTER COLUMN "UserId" TYPE text;
ALTER TABLE "Players" ALTER COLUMN "UserId" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210221172033_Changed_UserIds_To_Strings', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "TeamPlayerAssignmentEntity" DROP CONSTRAINT "FK_TeamPlayerAssignmentEntity_Players_PlayerId";

ALTER TABLE "TeamPlayerAssignmentEntity" DROP CONSTRAINT "FK_TeamPlayerAssignmentEntity_Teams_TeamId";

ALTER TABLE "TeamPlayerAssignmentEntity" DROP CONSTRAINT "PK_TeamPlayerAssignmentEntity";

ALTER TABLE "TeamPlayerAssignmentEntity" RENAME TO "TeamPlayerAssignments";

ALTER INDEX "IX_TeamPlayerAssignmentEntity_PlayerId" RENAME TO "IX_TeamPlayerAssignments_PlayerId";

ALTER TABLE "Players" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Players" ALTER COLUMN "Name" DROP NOT NULL;

ALTER TABLE "TeamPlayerAssignments" ADD CONSTRAINT "PK_TeamPlayerAssignments" PRIMARY KEY ("TeamId", "PlayerId");

ALTER TABLE "TeamPlayerAssignments" ADD CONSTRAINT "FK_TeamPlayerAssignments_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE;

ALTER TABLE "TeamPlayerAssignments" ADD CONSTRAINT "FK_TeamPlayerAssignments_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210228114645_ChangedTeamAssignementPropertyType', '5.0.1');

COMMIT;

