sudo: required

services:
  - docker

before_install:
  - cd src/backend/Playprism

script:
  - docker build -t blueh10/tournament.api:build -f Services/TournamentService/Playprism.Services.TournamentService.API/Dockerfile .

after_success:
  - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push blueh10/tournament.api:build
