# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push images
  jobs:  
  - job: SonarQube
    displayName: SonarQube analysis
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud connection'
        organization: 'lechniakamadeusz07'
        scannerMode: 'MSBuild'
        projectKey: 'lechniakamadeusz07_Playprism'
        projectName: 'Playprism'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.csproj'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '60'
  - job: Build
    dependsOn: SonarQube
    displayName: Build and Push images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'login'
    - task: Docker@2
      displayName: Build and Push ApiGateway
      inputs:
        command: buildAndPush
        repository: blueh10/apigateway
        Dockerfile: '**/ApiGateway/Playprism.ApiGateway/Dockerfile'
        buildContext: $(Build.Repository.LocalPath)/src/backend/Playprism
        tags: |
          build-on-agent
    - task: Docker@2
      displayName: Build and Push TournamentService
      inputs:
        command: buildAndPush
        repository: blueh10/tournament.api
        Dockerfile: '**/Services/TournamentService/Playprism.Services.TournamentService.API/Dockerfile'
        buildContext: $(Build.Repository.LocalPath)/src/backend/Playprism
        tags: |
          build-on-agent
    - task: Docker@2
      displayName: Build and Push TeamService
      inputs:
        command: buildAndPush
        repository: blueh10/team.api
        Dockerfile: '**/Services/TeamService/Playprism.Services.TeamService.API/Dockerfile'
        buildContext: $(Build.Repository.LocalPath)/src/backend/Playprism
        tags: |
          build-on-agent