CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Disciplines" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "LogoPath" text NULL,
    CONSTRAINT "PK_Disciplines" PRIMARY KEY ("Id")
);

CREATE TABLE "MatchDefinitions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TournamentId" integer NOT NULL,
    "ConfirmationNeeded" boolean NOT NULL,
    "NumberOfGames" integer NOT NULL,
    "ScoreBased" boolean NOT NULL,
    CONSTRAINT "PK_MatchDefinitions" PRIMARY KEY ("Id")
);

CREATE TABLE "Tournaments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DisciplineId" integer NOT NULL,
    "Platform" text NULL,
    "Name" text NULL,
    "OwnerId" integer NOT NULL,
    "AreTeams" boolean NOT NULL,
    "MaxNumberOfPlayers" integer NOT NULL,
    "Timezone" text NULL,
    "StartDate" timestamp without time zone NULL,
    "RegistrationEndDate" timestamp without time zone NULL,
    "CheckInDate" timestamp without time zone NULL,
    "CheckInTime" timestamp without time zone NULL,
    "Location" text NULL,
    "Website" text NULL,
    "LogoPath" text NULL,
    "Description" text NULL,
    "Prizes" text NULL,
    "Rules" text NULL,
    "RulesPath" text NULL,
    "ContactEmail" text NULL,
    "ContactNumber" text NULL,
    "Format" integer NOT NULL,
    "InviteOnly" boolean NOT NULL,
    "RegistrationApprovalNeeded" boolean NOT NULL,
    "MinNumberOfPlayersInTeam" integer NULL,
    "MaxNumberOfPlayersInTeam" integer NULL,
    "Published" boolean NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NULL,
    "Finished" boolean NOT NULL,
    "Aborted" boolean NOT NULL,
    CONSTRAINT "PK_Tournaments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tournaments_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rounds" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TournamentId" integer NOT NULL,
    "MatchDefinitionId" integer NOT NULL,
    "Order" integer NOT NULL,
    "NumberOfPlayers" integer NOT NULL,
    "NumberOfMatches" integer NOT NULL,
    "StartDate" timestamp without time zone NULL,
    "EndDate" timestamp without time zone NULL,
    "Finished" boolean NOT NULL,
    CONSTRAINT "PK_Rounds" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rounds_MatchDefinitions_MatchDefinitionId" FOREIGN KEY ("MatchDefinitionId") REFERENCES "MatchDefinitions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Participants" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TournamentId" integer NOT NULL,
    "ParticipantId" integer NOT NULL,
    "Name" text NULL,
    CONSTRAINT "PK_Participants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Participants_Tournaments_TournamentId" FOREIGN KEY ("TournamentId") REFERENCES "Tournaments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Matches" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TournamentId" integer NOT NULL,
    "RoundId" integer NOT NULL,
    "MatchDate" timestamp without time zone NULL,
    "Participant1Id" integer NOT NULL,
    "Participant2Id" integer NOT NULL,
    "Result" integer NOT NULL,
    "Played" boolean NOT NULL,
    "Confirmed" boolean NOT NULL,
    CONSTRAINT "PK_Matches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Matches_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Matches_Tournaments_TournamentId" FOREIGN KEY ("TournamentId") REFERENCES "Tournaments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Games" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MatchId" integer NOT NULL,
    "Score1" integer NOT NULL,
    "Score2" integer NOT NULL,
    "Description" text NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Games_Matches_MatchId" FOREIGN KEY ("MatchId") REFERENCES "Matches" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Games_MatchId" ON "Games" ("MatchId");

CREATE INDEX "IX_Matches_RoundId" ON "Matches" ("RoundId");

CREATE INDEX "IX_Matches_TournamentId" ON "Matches" ("TournamentId");

CREATE INDEX "IX_Participants_TournamentId" ON "Participants" ("TournamentId");

CREATE INDEX "IX_Rounds_MatchDefinitionId" ON "Rounds" ("MatchDefinitionId");

CREATE INDEX "IX_Tournaments_DisciplineId" ON "Tournaments" ("DisciplineId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210104195921_InitMigration', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rounds" RENAME COLUMN "NumberOfPlayers" TO "NumberOfCompetitors";

ALTER TABLE "Tournaments" ALTER COLUMN "Timezone" SET NOT NULL;
ALTER TABLE "Tournaments" ALTER COLUMN "Timezone" SET DEFAULT '';

ALTER TABLE "Tournaments" ALTER COLUMN "Platform" SET NOT NULL;
ALTER TABLE "Tournaments" ALTER COLUMN "Platform" SET DEFAULT '';

ALTER TABLE "Tournaments" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Tournaments" ALTER COLUMN "Name" SET DEFAULT '';

ALTER TABLE "Rounds" ADD "Started" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Participants" ADD "Approved" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Participants" ADD "RegistrationDate" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '0001-01-01 00:00:00';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210106132721_MinorAdjustments', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rounds" ADD "NextRoundId" integer NULL;

ALTER TABLE "Rounds" ADD "PreviousRoundId" integer NULL;

ALTER TABLE "MatchDefinitions" ADD "Name" text NOT NULL DEFAULT '';

CREATE INDEX "IX_Rounds_NextRoundId" ON "Rounds" ("NextRoundId");

CREATE INDEX "IX_Rounds_PreviousRoundId" ON "Rounds" ("PreviousRoundId");

ALTER TABLE "Rounds" ADD CONSTRAINT "FK_Rounds_Rounds_NextRoundId" FOREIGN KEY ("NextRoundId") REFERENCES "Rounds" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Rounds" ADD CONSTRAINT "FK_Rounds_Rounds_PreviousRoundId" FOREIGN KEY ("PreviousRoundId") REFERENCES "Rounds" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210106175033_MatchDefinitionsChanges', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Matches" ALTER COLUMN "Result" DROP NOT NULL;

ALTER TABLE "Matches" ALTER COLUMN "Participant2Id" DROP NOT NULL;

ALTER TABLE "Matches" ALTER COLUMN "Participant1Id" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210108191626_TableUpdates', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rounds" DROP CONSTRAINT "FK_Rounds_Rounds_NextRoundId";

ALTER TABLE "Rounds" DROP CONSTRAINT "FK_Rounds_Rounds_PreviousRoundId";

DROP INDEX "IX_Rounds_NextRoundId";

DROP INDEX "IX_Rounds_PreviousRoundId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210108202019_RemoveForeignKeys', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rounds" DROP COLUMN "NextRoundId";

ALTER TABLE "Rounds" DROP COLUMN "PreviousRoundId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210108202617_RemovedRounds', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Matches" ADD "PreviousMatch1Id" integer NULL;

ALTER TABLE "Matches" ADD "PreviousMatch2Id" integer NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210108222911_PreviousMatchidsAdded', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Matches" ADD "Participant1Score" integer NULL;

ALTER TABLE "Matches" ADD "Participant2Score" integer NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210109191152_AddParticipantResultsToMatchEntity', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Participants" DROP COLUMN "ParticipantId";

ALTER TABLE "Tournaments" ALTER COLUMN "OwnerId" TYPE text;

ALTER TABLE "Participants" ADD "UserId" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210220005519_ChangedAuth0IdsToString', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tournaments" ADD "Ongoing" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210304191225_Tournaments_Ongoing_Column', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tournaments" ADD "OwnerName" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210310234129_Add_OwnerName_Tournaments', '5.0.1');

COMMIT;

START TRANSACTION;

DROP TABLE "Games";

ALTER TABLE "Participants" ADD "PlayerId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Participants" ADD "TeamId" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210314083248_RemovedGamesTable', '5.0.1');

COMMIT;

